name: DLART
favicon: null
layout_spectrum: 0.51537
typography_spectrum: 0.5349409035407007
title: DAVID LYNCH ART paintings sculptures photography graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.9008798531722277
  lightness: 0.9938461903948337
  saturation: 0.10099427099339664
  rhythmicContrast: 0.99090487184003
purpose: []
