name: DLART
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11541
title: DAVID LYNCH ART paintings sculptures photography graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0
purpose: []
