name: DLART
favicon: null
layout_spectrum: 0.51537
typography_spectrum: 0.4590289746411145
title: DAVID LYNCH ART paintings sculptures photography graphics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.18225878663361073
  lightness: 0.1114008161239326
  saturation: 0.3967036698013544
  rhythmicContrast: 0.4955590795725584
purpose: []
